Controllers forms
dronky/ror_samurai_2 pull request #4
Opened 2017-08-14 16:03 UTC by dronky

Один момент — в задании говориться

> связанный с пользователем и содержащий нужную информацию

Но у нас в системе нет аутентификации (да мы ее еще и не проходили), поэтому привязать что либо к пользователю довольно проблематично. Пока просто в коде захардкодил `user:1`.

2017-08-16 14:21 UTC, psylone requested changes

2017-08-16 14:21 UTC, psylone commented on db/schema.rb
> +    t.string "wagon_type"
Для того чтобы STI работало правильно необходимо назвать колонку `type`, либо указать в модели что используется колонка `wagon_type`. В ином случае ты сейчас можешь выполнить:

```ruby
SvWagon.find(2)
```

Это вернёт объект класса `SvWagon`, не смотря на то что в `wagon_type` находится значение `SitWagon`.

2017-08-16 14:21 UTC, psylone commented on app/views/wagons/new.html.erb
> +      <%= f.select :wagon_type, @wagon.get_types %><br>
Логичней спрашивать типы у класса вагона, вместо объекта.

2017-08-16 14:21 UTC, psylone commented on app/views/wagons/new.html.erb
> +    </div>
Нет остальных типов мест.

2017-08-16 14:21 UTC, psylone commented on app/views/wagons/new.html.erb
> -<%= link_to 'Back', wagons_path %>
Навигация не помешает.

2017-08-16 14:21 UTC, psylone commented on app/views/wagons/index.html.erb
> +      </tr>
Это всё должно быть в паршиале. Здесь нужно рендерить коллекцию объектов:

```ruby
<%= render @wagons %>
```

2017-08-16 14:21 UTC, psylone commented on app/views/wagons/edit.html.erb
> +<%= render 'form', wagon: [@train, @wagon] %>
Почему здесь рендерим паршиал формы, а при создании нового вагона - нет?

2017-08-16 14:21 UTC, psylone commented on app/views/wagons/edit.html.erb
> +<%= render 'form', wagon: [@train, @wagon] %>
В паршиале формы также не хватает типов мест.

2017-08-16 14:21 UTC, psylone commented on app/views/users/index.html.erb
> +<% end %>
Почему мы относим получение формы поиска билетов к пользователю, а её обработку к маршрутам? Поиск - это самостоятельный ресурс который должен управляться собственным контроллером.

2017-08-16 14:21 UTC, psylone commented on app/views/users/index.html.erb
> +    <p>To: <%= select_tag 'station_last', options_for_select(RailwayStation.all.collect {|u| [u.title, u.id]}) %></p>
Посмотри в сторону хэлпера [collection_select](http://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-collection_select).

2017-08-16 14:21 UTC, psylone commented on app/views/trains/show.html.erb
> +        </ul>
Нет смысла делать новый список для каждого вагона. Должен быть один тэг `<ul>` для всего списка.

2017-08-16 14:21 UTC, psylone commented on app/views/trains/show.html.erb
> +          <li>Down seats: <%= @train.wagons.where(wagon_type: :PlackartWagon).sum(:down_seats) %></li>
Лучше сделать скоуп для вагонов чтобы можно было написать:

```ruby
@train.wagons.plackart.sum(:down_seats)
```

2017-08-16 14:21 UTC, psylone commented on app/models/train.rb
> +  end
Где используется этот метод?

2017-08-16 14:21 UTC, psylone commented on app/models/train.rb
>    def seats_count
Что именно считает этот метод: вагоны или места?

2017-08-16 14:21 UTC, psylone commented on app/models/train.rb
> +        RailwayStation.joins(:railway_stations_routes).where("station_number = 1").first
У нас поезд связан с маршрутом, а маршрут имеет станции. Поэтому должно быть что-то вроде этого:

```ruby
self.current_station = route.railway_stations.ordered.first
```

2017-08-16 14:21 UTC, psylone commented on app/models/train.rb
> +  before_validation :set_station
Я не думаю что перед каждым сохранением поезда нам нужно ставить его на первую станцию. Мы должны делать это только один раз перед созданием объекта.

2017-08-16 14:21 UTC, psylone commented on app/controllers/routes_controller.rb
> +    params.require(:route).permit(:name, :station_id)
Из какой формы приходит параметр `:station_id`?

2017-08-16 14:21 UTC, psylone commented on app/controllers/routes_controller.rb
> +    @station_last = params[:station_last]
Поиск является собственным ресурсом, им должен управлять отдельный контроллер.

2017-08-16 14:21 UTC, psylone commented on app/controllers/tickets_controller.rb
> +    params.require(:ticket).permit!
Лучше всё же перечислить список допустимых парамтеров даже если это все или пости все параметры что есть на данный момент.

2017-08-16 14:21 UTC, psylone commented on app/controllers/wagons_controller.rb
> +    if @wagon.save!
Это не сработает, потому что `save!` вызовет исключение, тогда как `save` вернёт `false` если объект не сохранится из-за ошибки.

2017-08-16 14:21 UTC, psylone commented on app/controllers/wagons_controller.rb
> +    params.require(:wagon).permit(:train_id, :wagon_type, :up_seats, :down_seats, :number)
Не хватает остальных типов мест.

2017-08-16 14:21 UTC, psylone commented on app/controllers/wagons_controller.rb
>  class WagonsController < ApplicationController
`index`, `new`, `create`, `show`, а где остальные экшены?

2017-08-16 14:21 UTC, psylone commented on app/controllers/wagons_controller.rb
> +    @wagon = Wagon.find(params[:id])
Поскольку вагоны теперь являются вложенным ресурсом, удалять вагон стоит через ассоциацию с поездом.

2017-08-16 14:21 UTC, psylone commented on app/models/route.rb
> +  end
Лучше вынести логику поиска в отдельный Ruby класс.

2017-08-16 14:21 UTC, psylone commented on app/models/route.rb
> +    RailwayStationsRoute.find_by(railway_station_id: station_id).station_departure
Здесь тоже можно сделать метод `station_route`.

2017-08-16 14:21 UTC, psylone commented on app/views/railway_stations/index.html.erb
>    <% end %>
Можно просто отрендерить коллекцию: `<%= render @railway_stations %>`.

2017-08-16 14:21 UTC, psylone commented on app/views/routes/_trains.html.erb
> +  <% @routes.each do |route| %>
У нас паршиал называется `_trains`, но итерация внутри него идёт по `@routes`. Будет лучше итерацию по маршрутам поместить в `app/views/routes/index.html.erb` (она, кстати там уже есть), а этот паршиал переименовать в `_train` и рендерить только эту часть:

```ruby
              <tr>
                <td><%= train.number %></td>
                <td><%= depature %></td>
                <td><%= arrival %></td>
                <td><%= link_to 'Buy tickets', new_ticket_path(train_id: train.id,
                                                               user_id: 1,
                                                               start_station_id: @station_first,
                                                               end_station_id: @station_last ) %></td>
              </tr>
```

2017-08-16 14:21 UTC, psylone commented on app/views/tickets/new.html.erb
> +    <%= f.hidden_field :end_station_id, value: @end_station_id %>
Не обязательно заводить инстанс переменные, в представлениях доступен метод `params`.

2017-08-16 14:21 UTC, psylone commented on app/views/tickets/show.html.erb
> +  <%= RailwayStation.find(@ticket.start_station_id).title %>
Зачем нам искать отдельно станцию, когда билет с ней уже связан:

```ruby
@ticket.start_station.title
```

2017-08-22 20:02 UTC, dronky commented on app/views/railway_stations/index.html.erb
>    <% end %>
Провозился 2 часа, но так и не понял, как рендерить коллекцию при одновременном использовании STI и вложенных ресурсов. При попытке рендерить коллекцию вагонов, я получаю ошибку, например: sit_wagons не существует, и это логично, т.к. я рендерю коллекцию вагонов, а не sit_wagons, как "прокинуть" sti ресурсы в коллекцию я так и не понял.

2017-08-24 00:33 UTC, psylone commented on app/controllers/search_controller.rb
> +  def set_search
Логичней назвать `set_search_result`.

2017-08-24 01:36 UTC, psylone requested changes

2017-08-24 01:36 UTC, psylone commented on app/models/search.rb
> +end
Зачем нам модель, мы же не сохраняем поиски в базе?

2017-08-24 01:36 UTC, psylone commented on app/controllers/routes_controller.rb
> +    @station_last = params[:station_last]
Теперь за это отвечает `SearchController`, лишний код нужно удалить.

2017-08-24 01:36 UTC, psylone commented on app/controllers/trains_controller.rb
> +    @train.set_station
Коллбэки должны быть приватными методами и не предназначены для вызова извне.

2017-08-24 01:36 UTC, psylone commented on app/controllers/wagons_controller.rb
> +        format.json { render json: @wagon.errors, status: :unprocessable_entity }
Представление ресурса в _JSON_ формате нам сейчас не нужно.

2017-08-24 01:36 UTC, psylone commented on app/controllers/wagons_controller.rb
> -  def edit
`edit` метод нам также необходим.

2017-08-24 01:36 UTC, psylone commented on app/controllers/wagons_controller.rb
> +    params.require(:wagon).permit(:train_id, :type, :up_seats, :down_seats, :number)
Не указаны остальные типы мест.

2017-08-24 01:36 UTC, psylone commented on app/models/railway_station.rb
> +    station_route(route).try(:station_number)
В Ruby `2.3+` можно использовать метод `&.`:

```ruby
station_route(route)&.station_number
``` 

Если слева `nil`, вернётся `nil`, если нет - будет вызван метод `station_number`.

2017-08-24 01:36 UTC, psylone commented on app/models/train.rb
> +  scope :sit, -> { where(type: 'Sit_wagon') }
Это скоупы для вагонов или поездов?

2017-08-24 01:36 UTC, psylone commented on app/models/train.rb
> +  def set_station
Коллбэк должен быть приватным методом.

2017-08-24 01:36 UTC, psylone commented on app/models/train.rb
> +    self.current_station = RailwayStation.find(station_id)
Что именно мы делаем здесь? Что будет если я попытаюсь изменить текущую станцию поезда?

2017-08-24 01:36 UTC, psylone commented on app/models/wagon.rb
> +  def set_number
`self.number ||= train.wagons.maximum(:number).to_i + 1`.

2017-08-24 01:36 UTC, psylone commented on app/views/railway_stations/index.html.erb
>    <% end %>
Конкретно здесь имелся в виду вариант:

```ruby
<%= render @railway_stations %>
```

2017-08-24 01:36 UTC, psylone commented on app/views/railway_stations/index.html.erb
>    <% end %>
Что касается рендеринга объектов STI, твой вариант `<%= render partial: "wagon", collection: @wagons, as: :wagon %>` рабочий.

В каком именно месте возникает ошибка?

2017-08-24 01:36 UTC, psylone commented on app/views/search/index.html.erb
> +    <%= collection_select(:station_last, :id, RailwayStation.all, :id, :title)  %>
Если передать `nil` в качестве первого аргумента, а `:last_station_id` в качестве второго, то можно будет в контроллере обращаться через `params[:last_station_id]`.

2017-08-24 01:36 UTC, psylone commented on app/views/users/index.html.erb
> +<% end %>
По-моему, этот шаблон нам больше не нужен.

2017-08-24 01:39 UTC, psylone commented
Удали плиз каталог `log` из репозитория и добавь его в `.gitignore`.

2017-08-26 16:39 UTC, psylone commented on app/controllers/routes_controller.rb
> +    @station_last = params[:station_last]
В отображении маршрутов нам не нужны две этих инстанс переменных с начальной и конечной станциями.

2017-08-26 16:40 UTC, psylone commented on app/views/routes/index.html.erb
> +<%= render partial: 'trains' if @station_first %>
Маршрут знает по ассоциации есть у него поезда или нет. Поэтому использовать отдельную инстанс переменную `@station_first` здесь не нужно.

2017-08-26 16:43 UTC, psylone commented on app/models/train.rb
> +    self.current_station = RailwayStation.find(station_id)
В чём заключается смысл автоматически каждый раз перед валидацией (а значит и сохранением) объекта назначать текущую станцию? Что если я захочу явно назначить **другую** текущую станцию?

2017-09-09 23:40 UTC, merged