Device
dronky/ror_samurai_2 pull request #5
Opened 2017-08-31 21:06 UTC by dronky

2017-09-02 00:02 UTC, psylone requested changes

2017-09-02 00:02 UTC, psylone commented on .gitignore
> +.idea/workspace.xml
Выше исключается весь каталог `.idea`, этого достаточно.

2017-09-02 00:02 UTC, psylone commented on app/controllers/admin/tickets_controller.rb
> +  before_action :authenticate_user!, only: [:create, :destroy]
Это админский контроллер, поэтому его ресурсы должны быть доступны **только** админу.

2017-09-02 00:02 UTC, psylone commented on app/views/admin/tickets/new.html.erb
> +    <!--Почему редиректит на метод create не в админ контроллере, а в обычном? (нужно явно указывать admin_tickets_path)-->
👍

2017-09-02 00:02 UTC, psylone commented on app/models/ticket.rb
> +  end
Лучше это сделать с помощью обратного вызова (коллбэка).

2017-09-02 00:02 UTC, psylone commented on app/controllers/admin/tickets_controller.rb
> +    @user_id = params[:ticket][:user_id]
Переменная экземпляра здесь не нужна, достаточно локальной. Но и её лучше избежать с помощью обратного вызова в модели `Ticket`, либо добавить поле в форму создания билета.

2017-09-02 00:02 UTC, psylone commented on app/controllers/tickets_controller.rb
> +  before_action :authenticate_user!, only: [:create, :destroy]
Если мы защищаем только `create` и `destroy`, чей список билетов будет показан в `index`? На мой взгляд, это должен быть список билетов конкретного пользователя.

2017-09-02 00:02 UTC, psylone commented on app/controllers/tickets_controller.rb
> +    @tickets = Ticket.all
Я бы не хотел чтобы мои билеты видел кто-то другой.

2017-09-02 00:02 UTC, psylone commented on app/controllers/tickets_controller.rb
> +    if @ticket.save!
Это не сработает, потому что если билет не сохранится, выбросится исключение и на этом метод прекратит свою работу.

2017-09-02 00:02 UTC, psylone commented on app/controllers/tickets_controller.rb
>      @ticket.destroy
Есть возможность подменить идентификатор и удалить чужой билет.

2017-09-02 00:02 UTC, psylone commented on app/views/layouts/application.html.erb
> +<% end %>
Это можно вынести в хэлпер.

2017-09-02 00:02 UTC, psylone commented on app/views/tickets/index.html.erb
> +<% if current_user.admin? %>
Это должны быть 2 разных шаблона.

2017-09-02 00:02 UTC, psylone commented on db/migrate/20170808211421_change_wagons.rb
> +    rename_column(:wagons, :number, :number)
Похоже что название атрибутов одинаковые или что-то упускаю?

2017-09-03 22:18 UTC, psylone commented on app/controllers/admin/tickets_controller.rb
> +    params.require(:ticket).permit(:train_id, :user_id, :full_name, :start_station_id, :end_station_id)
Поскольку используем обратный вызов, здесь `:full_name` не нужен.

2017-09-03 22:18 UTC, psylone approved these changes

2017-09-03 22:21 UTC, psylone commented on app/views/admin/tickets/new.html.erb
> +    <!--Почему редиректит на метод create не в админ контроллере, а в обычном? (нужно явно указывать admin_tickets_path)-->
Сорри, подумал `url: admin_tickets_path` это ответ )

URL строится на основе класса модели. Чтобы исползовать нэймспэйс можно сделать так:

```ruby
<%= form_for [:admin, @ticket] do |form| %>
<% end %>
```

2017-09-04 12:33 UTC, dronky commented on app/views/admin/tickets/new.html.erb
> +    <!--Почему редиректит на метод create не в админ контроллере, а в обычном? (нужно явно указывать admin_tickets_path)-->
Почему редиректит на метод create не в админ контроллере, а в обычном? (нужно явно указывать admin_tickets_path)

2017-09-04 12:33 UTC, dronky commented on app/controllers/admin/tickets_controller.rb
> +    @ticket.full_name = @ticket.get_user_name(@user_id.to_i)
Сделал такую штуку, чтобы в момент создания тикета автоматически вносилось имя покупателя в базу, изначально хотел сделать в модели коллбек, но потом понял, что модель трогать нельзя, т.к. она общая на оба контроллера.

Вообще это приемлемая реализация? Или можно лучше?)

2017-09-04 12:33 UTC, dronky commented on app/views/admin/wagons/index.html.erb
> +<%= link_to 'New Wagon', new_admin_train_wagon_path(train_id: 1) %>
Пришлось захардкодить `1`, т.к. ранее создание вагона было возможно только со страницы поезда, сейчас эта кнопка находится на общей странице с вагоном и нет привязки к поезду, т.к. стандартный роут не работает.

В этом случае надо отдельную страницу пилить для создания вагона (с выбором типа вагона и поезда), так?

2017-09-04 12:33 UTC, dronky commented on app/views/admin/wagons/_wagon.html.erb
> +  <td><%= link_to 'Edit', edit_polymorphic_path([:admin, wagon]) %></td>
Только гугл помог в том, что эта строчка работает. :) На Stackoverflow нашел подобный вопрос, но там не объяснялось, почему первым аргументом должен идти `:admin`, где этот первый аргумент используется и откуда тянется `:admin`?

2017-09-04 12:33 UTC, dronky commented on app/views/admin/wagons/_wagon.html.erb
> +  <td><%= link_to 'Edit', edit_polymorphic_path([:admin, wagon]) %></td>
@psylone посмотри на вопрос, пожалуйста. :) Как вообще лучше здавать вопросы, чтобы ты их увидел?

2017-09-04 12:33 UTC, dronky commented on app/views/admin/wagons/index.html.erb
> +<%= link_to 'New Wagon', new_admin_train_wagon_path(train_id: 1) %>
@psylone посмотри на вопрос, пожалуйста. :) Как вообще лучше здавать вопросы, чтобы ты их увидел?

2017-09-09 23:40 UTC, merged